Repository IATI/IATI-Codelists, pull requests merged in 2018-02, with the labels that each got.

#126 [1.04] Remove various Codelists from being Embedded
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/PolicyMarker.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/TiedStatus.xml
  xml/VerificationStatus.xml
Labels: complete

#127 [1.05] Remove various Codelists from being Embedded
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/PolicyMarker.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/TiedStatus.xml
  xml/VerificationStatus.xml
Labels: complete

#128 [2.01] Remove various Codelists from being Embedded
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/CRSAddOtherFlags.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/OtherIdentifierType.xml
  xml/PolicyMarker.xml
  xml/PolicyMarkerVocabulary.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/SectorVocabulary.xml
  xml/TiedStatus.xml
  xml/VerificationStatus.xml
Labels: complete

#129 [2.02] Remove various Codelists from being Embedded
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/CRSAddOtherFlags.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/OtherIdentifierType.xml
  xml/PolicyMarker.xml
  xml/PolicyMarkerVocabulary.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/SectorVocabulary.xml
  xml/TiedStatus.xml
  xml/VerificationStatus.xml
Labels: complete

#130 [hc] Remove various Codelists from being Embedded
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/CRSAddOtherFlags.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/OtherIdentifierType.xml
  xml/PolicyMarker.xml
  xml/PolicyMarkerVocabulary.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/SectorVocabulary.xml
  xml/TiedStatus.xml
  xml/VerificationStatus.xml
Labels: complete

#136 Add iati-activity/tag/@vocabulary to codelist mapping file
  mapping.xml
Labels: complete, enhancement

#137 Re-add removed 2.03 mappings
  mapping.xml
Labels: bug, complete

#134 Merge 2.03 development to 2.03 live branch
  mapping.xml
  xml/ActivityScope.xml
  xml/BudgetIdentifier.xml
  xml/BudgetIdentifierSector-category.xml
  xml/BudgetIdentifierSector.xml
  xml/BudgetIdentifierVocabulary.xml
  xml/CRSAddOtherFlags.xml
  xml/ConditionType.xml
  xml/ContactType.xml
  xml/DescriptionType.xml
  xml/DisbursementChannel.xml
  xml/DocumentCategory-category.xml
  xml/GeographicExactness.xml
  xml/GeographicLocationClass.xml
  xml/GeographicLocationReach.xml
  xml/GeographicVocabulary.xml
  xml/GeographicalPrecision.xml
  xml/IndicatorMeasure.xml
  xml/LoanRepaymentPeriod.xml
  xml/LoanRepaymentType.xml
  xml/OrganisationType.xml
  xml/OtherIdentifierType.xml
  xml/PolicyMarker.xml
  xml/PolicyMarkerVocabulary.xml
  xml/PublisherType.xml
  xml/RegionVocabulary.xml
  xml/ResultType.xml
  xml/SectorVocabulary.xml
  xml/TiedStatus.xml
  xml/TransactionType.xml
  xml/VerificationStatus.xml
Labels: complete
